revert to previous flutter analyze

diff --git a/.github/workflows/analyze_and_test.yml b/.github/workflows/analyze_and_test.yml
--- a/.github/workflows/analyze_and_test.yml
+++ b/.github/workflows/analyze_and_test.yml
@@ -13,15 +13,19 @@ jobs:
         channel: 'stable'
         flutter-version: '3.27.3'   
 
-    - run: flutter pub get
-
-    - name: Analyze Dart
-      uses: zgosalvez/github-actions-analyze-dart@v3
-      with:
-        fail-on-infos: false
-        fail-on-warnings: true
-        working-directory: ./
-        line-length: 120
+    - name: Statically analyze the Dart code for any errors/warnings, ignoring "info" level warnings
+      run: |
+        output=$(flutter analyze 2>&1)
+        echo "$output"
+        if echo "$output" | grep -q -E 'error|warning'; 
+        then
+          echo "Analysis found errors or warnings:"
+          echo "$output"
+          exit 1
+        else
+          echo "No errors or warnings found."
+          exit 0
+        fi
 
     - name: Test
       run: flutter test
