Fix Flutter analyze not detecting "warning" and "error" due to formatting (#249)
* check format of warning and error

* display output

* print the error output

* try using an extension

* add params

* fail-on-warnings: true

* revert to previous flutter analyze

* run only flutter analyze

* try to display analysis error on ga

* try proposed command

* Revert "try proposed command"

This reverts commit 86c55997e19d953ff8114b9e0650a74af8ff0af5.

* try with tee

diff --git a/.github/workflows/analyze_and_test.yml b/.github/workflows/analyze_and_test.yml
--- a/.github/workflows/analyze_and_test.yml
+++ b/.github/workflows/analyze_and_test.yml
@@ -15,10 +15,13 @@ jobs:
 
     - name: Statically analyze the Dart code for any errors/warnings, ignoring "info" level warnings
       run: |
-        if flutter analyze 2>&1 | grep -q -E 'error:|warning:'; 
-        then exit 1
-        else exit 0
+        flutter analyze 2>&1 | tee flutter_analyze.log
+        if grep -q -E -i 'error|warning' flutter_analyze.log; then
+            exit 1
+        else
+          echo "No errors or warnings found."
+          exit 0
         fi
- 
+
     - name: Test
       run: flutter test
