display output

diff --git a/.github/workflows/analyze_and_test.yml b/.github/workflows/analyze_and_test.yml
--- a/.github/workflows/analyze_and_test.yml
+++ b/.github/workflows/analyze_and_test.yml
@@ -15,9 +15,16 @@ jobs:
 
     - name: Statically analyze the Dart code for any errors/warnings, ignoring "info" level warnings
       run: |
-        if flutter analyze 2>&1 | grep -q -E 'error|warning'; 
-        then exit 1
-        else exit 0
+        output=$(flutter analyze 2>&1)
+        echo "$output"
+        if echo "$output" | grep -q -E 'error|warning'; 
+        then
+          echo "Analysis found errors or warnings:"
+          echo "$output" | grep -E 'error|warning'
+          exit 1
+        else
+          echo "No errors or warnings found."
+          exit 0
         fi
  
     - name: Test
