try to display analysis error on ga

diff --git a/.github/workflows/analyze_and_test.yml b/.github/workflows/analyze_and_test.yml
--- a/.github/workflows/analyze_and_test.yml
+++ b/.github/workflows/analyze_and_test.yml
@@ -15,7 +15,15 @@ jobs:
 
     - name: Statically analyze the Dart code for any errors/warnings, ignoring "info" level warnings
       run: |
-        flutter analyze
+        if flutter analyze 2>&1 | grep -q -E 'error|warning';
+        then
+          echo "Analysis found errors or warnings:"
+          flutter analyze
+          exit 1
+        else
+          echo "No errors or warnings found."
+          exit 0
+        fi
 
     - name: Test
       run: flutter test
