iOS build with incorrect pubspec.lock

diff --git a/.github/workflows/build_app.yml b/.github/workflows/build_app.yml
--- a/.github/workflows/build_app.yml
+++ b/.github/workflows/build_app.yml
@@ -52,5 +52,12 @@ jobs:
 
     - run: flutter pub get
 
+    - name: Validate pubspec.lock is up to date
+      run: |
+        if ! git diff --quiet pubspec.lock; then
+          echo "::error ::pubspec.lock is out of date. Run 'flutter pub get' and commit the updated file."
+          exit 1
+        fi
+
     - name: Build ios
       run: flutter build ios --release --no-codesign
